export enum ZONE_PROFILE_TYPE {
  강당 = "강당",
  강의실 = "강의실",
  객실 = "객실",
  "교실(초중고)" = "교실(초중고)",
  구내식당 = "구내식당",
  "그 외 체류공간" = "그 외 체류공간",
  대규모사무실 = "대규모사무실",
  매장 = "매장",
  병실 = "병실",
  부속공간 = "부속공간",
  소규모사무실 = "소규모사무실",
  열람실 = "열람실",
  전산실 = "전산실",
  전시실 = "전시실",
  주거공간 = "주거공간",
  "주방 및 조리실" = "주방 및 조리실",
  "창고/설비/문서실" = "창고/설비/문서실",
  체육시설 = "체육시설",
  화장실 = "화장실",
  "회의 및 세미나실" = "회의 및 세미나실",
}

export const ZONE_PROFILE_TYPE_LABELS: Record<ZONE_PROFILE_TYPE, string> = {
  [ZONE_PROFILE_TYPE.강당]: "강당",
  [ZONE_PROFILE_TYPE.강의실]: "강의실",
  [ZONE_PROFILE_TYPE.객실]: "객실",
  [ZONE_PROFILE_TYPE.구내식당]: "구내식당",
  [ZONE_PROFILE_TYPE.대규모사무실]: "대규모사무실",
  [ZONE_PROFILE_TYPE.매장]: "매장",
  [ZONE_PROFILE_TYPE.병실]: "병실",
  [ZONE_PROFILE_TYPE.부속공간]: "부속공간",
  [ZONE_PROFILE_TYPE.소규모사무실]: "소규모사무실",
  [ZONE_PROFILE_TYPE.열람실]: "열람실",
  [ZONE_PROFILE_TYPE.전산실]: "전산실",
  [ZONE_PROFILE_TYPE.전시실]: "전시실",
  [ZONE_PROFILE_TYPE.주거공간]: "주거공간",
  [ZONE_PROFILE_TYPE.체육시설]: "체육시설",
  [ZONE_PROFILE_TYPE.화장실]: "화장실",
  [ZONE_PROFILE_TYPE["교실(초중고)"]]: "교실(초중고)",
  [ZONE_PROFILE_TYPE["그 외 체류공간"]]: "그 외 체류공간",
  [ZONE_PROFILE_TYPE["주방 및 조리실"]]: "주방 및 조리실",
  [ZONE_PROFILE_TYPE["창고/설비/문서실"]]: "창고/설비/문서실",
  [ZONE_PROFILE_TYPE["회의 및 세미나실"]]: "회의 및 세미나실",
} as const;
